name: Test Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: print github values to test

    steps:
      - name: print github values
        run: | 
          echo "github.base_ref=${{github.base_ref}}"
          echo "github.head_ref=${{github.head_ref}}"
          echo "github.ref=${{github.ref}}"
          echo "github.ref=${{github.ref}}"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"